---
- name: Format the data volume
  community.general.filesystem:
    fstype: ext4
    dev: "{{ postgresql_data_device }}"
  when: postgresql_data_device is defined

- name: Create PostgreSQL data directory
  file:
    path: "{{ postgresql_data_dir }}"
    state: directory
    mode: '0755'

- name: Mount data volume
  mount:
    path: "{{ postgresql_data_dir }}"
    src: "{{ postgresql_data_device }}"
    fstype: ext4
    state: mounted
  when: postgresql_data_device is defined

- name: Create base data directory
  file:
    path: "/data"
    state: directory
    mode: '0755'