version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: ${IMAGE_PREFIX:-ghcr.io/meridian-analytics}/maipl-backend/ketos-backend:dev

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    image: ${IMAGE_PREFIX:-ghcr.io/meridian-analytics}/maipl-backend/ketos-worker:dev
