version: '3'

services:

  # Database
  db:
    image: "postgres:13"
    container_name: maipl_db
    env_file:
      - ../config/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped

  # Redis, file cache management
  redis:
    image: "redis:latest"
    container_name: maipl_redis
    hostname: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Minio, file storage
  minio:
    image: minio/minio
    command: server /data --address :9000 --console-address :9001
    env_file:
      - ../config/.env
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - /mnt/minio-data:/data
    restart: unless-stopped
    container_name: maipl_files_minio

  # RabbitMQ, message broker
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    container_name: maipl_message_broker
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped

  # Backend
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: maipl_backend
    ports:
      - "${DJANGO_PORT:-8000}:8000"
    volumes:
      - ../src:/backend
      - ../logs:/logs
      - ${FILE_CACHE_LOCATION:-/mnt/file_cache}:/cache
      - ${TASKS_LOCAL_STORAGE:-/mnt/tasks}:/tasks
    env_file:
      - ../config/.env
    command: /backend/entrypoint.backend.sh
    restart: unless-stopped
    depends_on:
      - minio
      - rabbit
      - db
      - redis

  # Celery worker
  worker:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    command: /backend/entrypoint.worker.sh
    volumes:
      - ../src:/backend
      - ../logs:/logs
      - ${FILE_CACHE_LOCATION:-/mnt/file_cache}:/cache
      - ${TASKS_LOCAL_STORAGE:-/mnt/tasks}:/tasks
    env_file:
      - ../config/.env
    container_name: maipl_ketos_worker
    depends_on:
      - minio
      - rabbit
      - backend
      - db
      - redis

volumes:
  db_data:
    name: backend_db_data
  redis_data:
    name: redis_data

