version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: registry.maipl-dev.com/maipl-backend/ketos-backend:dev
    container_name: ketos-backend
    ports:
      - "${DJANGO_PORT:-8000}:8000"
    volumes:
      - ../logs:/logs
      - ${FILE_CACHE_LOCATION:-/mnt/file_cache}:/cache
      - ${TASKS_LOCAL_STORAGE:-/mnt/tasks}:/tasks
    command: /backend/entrypoint.backend.sh
    env_file:
      - .env

      
