version: '3'

services:
  worker:
    image: registry.maipl-dev.com/maipl-backend/ketos-worker:dev
    container_name: ketos-worker
    volumes:
      - ../logs:/logs
      - ${FILE_CACHE_LOCATION:-/mnt/file_cache}:/cache
      - ${TASKS_LOCAL_STORAGE:-/mnt/tasks}:/tasks
    command: /backend/entrypoint.worker.sh
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [utility, compute, video]
