# Generated by Django 4.2.1 on 2024-04-10 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0010_alter_file_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, help_text='Description of the metrics task', max_length=255, null=True)),
                ('type', models.CharField(default='continuous', help_text='Type of the metrics task', max_length=64)),
                ('threshold_min', models.FloatField(default=0, help_text='Minimum threshold value', null=True)),
                ('threshold_max', models.FloatField(default=1, help_text='Maximum threshold value', null=True)),
                ('threshold_increment', models.FloatField(default=0.05, help_text='Threshold increment value', null=True)),
                ('total_time_units', models.FloatField(default=1, help_text='The total duration in arbitrary time units over which the detections were made (e.g., hours, minutes).', null=True)),
                ('add_bg_ref', models.BooleanField(default=False, help_text="Create background reference for audio files given a set of existing annotations. The 'reference' annotations will be updated to include the new annotations. Pass two parameters: [path_to_audio_folder, label].", null=True)),
                ('bg_label', models.CharField(blank=True, default=None, help_text='The second parameter that is the label assigned to the background noise. ', max_length=64, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('STARTED', 'Started'), ('FAILURE', 'Failure'), ('SUCCESS', 'Success')], default='CREATED', help_text='Status of the metrics task', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the metrics task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the metrics task was last updated')),
                ('bg_audio_list', models.ManyToManyField(help_text='List of audio files', related_name='audio_list_metrics_tasks', to='file.file')),
                ('eval_file', models.ForeignKey(help_text='Evaluation file', on_delete=django.db.models.deletion.CASCADE, related_name='eval_file_metrics_tasks', to='file.file')),
                ('output_files', models.ManyToManyField(help_text='List of output files', related_name='output_files_metrics_tasks', to='file.file')),
                ('ref_file', models.ForeignKey(help_text='Reference file', on_delete=django.db.models.deletion.CASCADE, related_name='ref_file_metrics_tasks', to='file.file')),
                ('user', models.ForeignKey(help_text='User who created the metrics task', on_delete=django.db.models.deletion.CASCADE, related_name='metrics_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
