# Generated by Django 4.2.1 on 2024-04-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricstask',
            name='folder',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
    ]
