# Generated by Django 4.2.1 on 2025-04-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_metricstask_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricstask',
            name='add_bg_ref',
        ),
        migrations.RemoveField(
            model_name='metricstask',
            name='bg_label',
        ),
        migrations.RemoveField(
            model_name='metricstask',
            name='threshold_increment',
        ),
        migrations.RemoveField(
            model_name='metricstask',
            name='threshold_max',
        ),
        migrations.RemoveField(
            model_name='metricstask',
            name='threshold_min',
        ),
        migrations.RemoveField(
            model_name='metricstask',
            name='total_time_units',
        ),
        migrations.RemoveField(
            model_name='metricstask',
            name='type',
        ),
        migrations.AddField(
            model_name='metricstask',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Parameters for the metrics task including type, thresholds, time units, and background settings'),
        ),
        migrations.AlterField(
            model_name='metricstask',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STARTED', 'Started'), ('RUNNING', 'Running'), ('FAILURE', 'Failure'), ('SUCCESS', 'Success')], default='CREATED', help_text='Status of the metrics task', max_length=10),
        ),
    ]
