# Generated by Django 4.2.1 on 2025-07-29 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0013_alter_file_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Human-readable task name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional task description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Task creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='active', help_text='Current task status', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for overall task processing', max_length=255, null=True, unique=True)),
                ('database_selection', models.JSONField(default=dict, help_text='Database selection mode and configuration')),
                ('output_settings', models.JSONField(default=dict, help_text='Database generation parameters and settings')),
                ('database_metadata', models.JSONField(default=dict, help_text='HDF5 structure and database metadata')),
                ('database_file', models.ForeignKey(blank=True, help_text='Generated database file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_file_tasks', to='file.file')),
                ('user', models.ForeignKey(help_text='User who created the task', on_delete=django.db.models.deletion.CASCADE, related_name='database_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group path identifier (e.g., /train, /test)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Group creation timestamp')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('imported', 'Imported')], default='in_progress', help_text='Current group status', max_length=20)),
                ('source', models.CharField(choices=[('new_group', 'New Group'), ('existing_database', 'Existing Database')], default='new_group', help_text='Group source type', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for group processing', max_length=255, null=True, unique=True)),
                ('config', models.JSONField(default=dict, help_text='Audio processing configuration including file IDs, annotations, etc.')),
                ('statistics', models.JSONField(default=dict, help_text='Processing results and statistics')),
                ('task', models.ForeignKey(help_text='Parent database task', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='dbtool.databasetask')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('task', 'name')},
            },
        ),
    ]
