# Generated by Django 4.2.1 on 2025-08-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasetask',
            name='local_path',
            field=models.CharField(blank=True, help_text='Local path for task files', max_length=255, null=True),
        ),
    ]
