# Generated by Django 4.2.1 on 2025-08-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtool', '0002_databasetask_local_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasegroup',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('imported', 'Imported'), ('error', 'Error')], default='in_progress', help_text='Current group status', max_length=20),
        ),
        migrations.AlterField(
            model_name='databasetask',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('error', 'Error')], default='active', help_text='Current task status', max_length=20),
        ),
    ]
