version: '3.8'

services:
  frontend-apps:
    build: 
      context: . 
      dockerfile: Dockerfile
      args:
        - NODE_ENV=staging
    ports:
      - 80:80
    volumes:
      - ./apps:/app/apps
    command: nginx -g 'daemon off;'
