# Frontend server configuration for all environments
server {
    listen 80;
    
    # Domain configurations:
    # - test.maipl.meridian.cs.dal.ca: Testing/staging environment
    # - demo.maipl.meridian.cs.dal.ca: Demo environment
    # - maipl.meridian.cs.dal.ca: Production environment
    server_name test.maipl.meridian.cs.dal.ca demo.maipl.meridian.cs.dal.ca maipl.meridian.cs.dal.ca;

    # Add root redirect to file-service
    location = / {
        return 301 /file-service/dashboard;
    }

    location /annotation-tool {
        alias /usr/share/nginx/html/annotation-tool/;
        try_files $uri /annotation-tool/index.html;
    }

    location /authentication-service {
        alias /usr/share/nginx/html/authentication-service/;
        try_files $uri /authentication-service/index.html;
    }

    location /file-service {
        alias /usr/share/nginx/html/file-service/;
        try_files $uri /file-service/index.html;
    }

    location /metrics {
        alias /usr/share/nginx/html/metrics/;
        try_files $uri /metrics/index.html;
    }

    location /model-runner {
        alias /usr/share/nginx/html/model-runner/;
        try_files $uri /model-runner/index.html;
    }

    location /model-trainer {
        alias /usr/share/nginx/html/model-trainer/;
        try_files $uri /model-trainer/index.html;
    }

    location /database-tool {
        alias /usr/share/nginx/html/database-tool/;
        try_files $uri /database-tool/index.html;
    }
}
