server {
    listen 4000;
    server_name test.maipl-dev.com;

    location /annotation-tool {
        alias /usr/share/nginx/html/annotation-tool/;
        try_files $uri /annotation-tool/index.html;
    }

    location /authentication-service {
        alias /usr/share/nginx/html/authentication-service/;
        try_files $uri /authentication-service/index.html;
    }

    location /file-service {
        alias /usr/share/nginx/html/file-service/;
        try_files $uri /file-service/index.html;
    }

    location /metrics {
        alias /usr/share/nginx/html/metrics/;
        try_files $uri /metrics/index.html;
    }

    location /model-runner {
        alias /usr/share/nginx/html/model-runner/;
        try_files $uri /model-runner/index.html;
    }

    location /model-trainer {
        alias /usr/share/nginx/html/model-trainer/;
        try_files $uri /model-trainer/index.html;
    }
}
