<<<<<<< HEAD
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  docs: [
    "intro",
    "what-is-maipl",
    {
      type: "category",
      label: "Helper Docs",
      items: ["helpers/helper-doc"],
    },
  ],
=======
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
>>>>>>> 919c8395 (added docusaurus doc files)
};

export default sidebars;
