pipeline {
    agent any

    environment {
        REGISTRY_URL = 'registry.maipl-dev.com'
    }

    stages {
        stage('Load Environment Variables') {
            steps {
                withCredentials([file(credentialsId: 'env-file-stage', variable: 'ENV_FILE')]) {
                    script {
                        def props = readProperties file: env.ENV_FILE
                        props.each { key, value ->
                            env."${key}" = "${value}"
                        }
                        echo "DJANGO environment is ${env.DJANGO_ENV}"
                    }
                }
            }
        }

        stage('Check Docker Registry') {
            steps {
                script {
                    try {
                        sh 'docker --version'
                        docker.withRegistry("https://${env.REGISTRY_URL}", 'docker-registry-credentials') {
                            echo "Docker registry is reachable"
                        }
                    } catch (Exception e) {
                        echo "Failed to reach Docker registry: ${e.message}"
                        error message: "Stopping the pipeline due to Docker registry connectivity issues."
                    }
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    echo "Building images"
                    sh 'docker compose -f compose/docker-compose.build.yml build'
                    echo "Build completed"
                    echo "Pushing images to registry"
                    docker.withRegistry("https://${env.REGISTRY_URL}", 'docker-registry-credentials') {
                        echo "Pushing backend image"
                        docker.image("${env.REGISTRY_URL}/maipl-backend/ketos-backend:dev").push('dev')
                        echo "Pushing worker image"
                        docker.image("${env.REGISTRY_URL}/maipl-backend/ketos-worker:dev").push('dev')
                    }
                    echo "Push completed"
                }
            }
        }

        stage('Cleanup') {
            steps {
                script {
                    echo "Cleaning up docker images"
                    sh 'docker system prune -f'
                }
            }
        }
    }
}