import os
import shutil
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver

from user.models import User
from file.models import File

class TrainingTask(models.Model):
    #
    # TrainingTask model
    # This model is used to store information about a training task.
    #
    TASK_STATUS = [
        ('CREATED', 'Created'), 
        ('PENDING', 'Pending'),
        ('STARTED', 'Started'),
        ('RUNNING', 'Running'),
        ('SUCCESS', 'Success'),
        ('FAILURE', 'Failure'),
        ('RETRY', 'Retry'),
        ('REVOKED', 'Revoked'),
    ]

    class Meta:
        ordering = ['id']

    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True, default=None)
    dataset_file = models.ForeignKey(File, null=True, blank=True, default=None, on_delete=models.SET_NULL, related_name='dataset_file_tasks', help_text='Dataset file to use for training')
    recipe_file = models.ForeignKey(File, null=True, blank=True, default=None, on_delete=models.SET_NULL, related_name='recipe_file_tasks', help_text='Recipe file to use for training')
    model_file = models.ForeignKey(File, null=True, blank=True, default=None, on_delete=models.SET_NULL, related_name='model_file_train_tasks', help_text='Model file generated by the training task')
    dataset_config = models.JSONField()
    options = models.JSONField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='train_tasks')
    status = models.CharField(max_length=255, default="CREATED", choices=TASK_STATUS)
    celery_task_id = models.CharField(max_length=255, unique=True, null=True, default=None, blank=True)
    local_path = models.CharField(max_length=255, null=True, default=None, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    def get_log(self):
        log_file_path = os.path.join(self.local_path, "training_log.csv")
        return self._transform_csv_for_chartjs(log_file_path)

    def get_console_output(self):
        console_output_file_path = os.path.join(self.local_path, "console.txt")
        return {
            "console_output": open(console_output_file_path, "r").read()
        }

    def _transform_csv_for_chartjs(self, csv_file_path):
        import csv
        import json

        with open(csv_file_path, 'r') as csvfile:
            csvreader = csv.DictReader(csvfile)
            data = list(csvreader)

        # Initialize the structure
        chart_data = {
            'labels': [],
            'datasets': []
        }

        # Determine unique datasets and metrics
        datasets = set()
        metrics = set()
        for row in data:
            datasets.add(row['dataset'])
            for key in row.keys():
                if key not in ['dataset', 'epoch']:
                    metrics.add(key)

        # Create datasets for each metric and dataset combination
        colors = ['rgb(255, 99, 132)', 'rgb(54, 162, 235)', 'rgb(75, 192, 192)', 'rgb(153, 102, 255)']
        color_index = 0
        for metric in metrics:
            for dataset in datasets:
                chart_data['datasets'].append({
                    'label': f'{dataset.capitalize()} {metric}',
                    'data': [],
                    'borderColor': colors[color_index % len(colors)],
                    'tension': 0.1
                })
                color_index += 1

        # Populate the data
        for row in data:
            if row['dataset'] == list(datasets)[0]:  # Only add labels once
                chart_data['labels'].append(int(row['epoch']))
            
            for i, dataset in enumerate(chart_data['datasets']):
                if dataset['label'].lower().startswith(row['dataset']):
                    metric = dataset['label'].split()[-1]
                    dataset['data'].append(float(row[metric]))

        return chart_data

@receiver(pre_delete, sender=TrainingTask)
def delete_local_path(sender, instance, **kwargs):
    if instance.local_path:
        shutil.rmtree(instance.local_path, ignore_errors=True)