# Generated by Django 4.2.1 on 2023-09-28 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0005_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRunnerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, help_text='Description of the model runner task', max_length=255, null=True)),
                ('celery_task_id', models.CharField(blank=True, default=None, help_text='Celery task id', max_length=255, null=True, unique=True)),
                ('threshold', models.FloatField(default=0.5, help_text='The threshold value used to determine the cut-off point for detections', null=True)),
                ('step_size', models.FloatField(default=None, help_text='Step size in seconds', null=True)),
                ('batch_size', models.IntegerField(default=32, help_text='How many samples will be loaded into memory', null=True)),
                ('merge_detections', models.BooleanField(default=False, help_text='A flag indicating whether to merge overlapping detections into a single detection.', null=True)),
                ('overwrite', models.BooleanField(default=True, help_text='Overwrites the detections, otherwise appends to it', null=True)),
                ('buffer', models.FloatField(default=0.0, help_text='The buffer duration to be added to each detection in seconds', null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('STARTED', 'Started'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('REVOKED', 'Revoked'), ('SUCCESS', 'Success')], default='CREATED', help_text='Status of the model runner task', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the model runner task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the model runner task was last updated')),
                ('detections', models.ForeignKey(blank=True, default=None, help_text='Detections file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections_tasks', to='file.file')),
                ('filelist', models.ManyToManyField(help_text='List of files to process', related_name='filelist_tasks', to='file.file')),
                ('model_file', models.ForeignKey(blank=True, default=None, help_text='Model file to use for processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_file_tasks', to='file.file')),
                ('user_id', models.ForeignKey(help_text='User who created the model runner task', on_delete=django.db.models.deletion.CASCADE, related_name='model_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField(help_text='Start')),
                ('end', models.FloatField(help_text='End')),
                ('score', models.FloatField(help_text='score')),
                ('label', models.CharField(help_text='Label', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the detection was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the detection was last updated')),
                ('file', models.ForeignKey(help_text='File', on_delete=django.db.models.deletion.CASCADE, related_name='file_detections', to='file.file')),
                ('task', models.ForeignKey(help_text='Model runner task', on_delete=django.db.models.deletion.CASCADE, related_name='task_detections', to='modelrunner.modelrunnertask')),
                ('user_id', models.ForeignKey(help_text='User who created the detection', on_delete=django.db.models.deletion.CASCADE, related_name='user_detections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
