# Generated by Django 4.2.1 on 2023-11-29 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelrunner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelrunnertask',
            options={'ordering': ['id']},
        ),
    ]
