# Generated by Django 4.2.1 on 2025-04-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelrunner', '0002_alter_modelrunnertask_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelrunnertask',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='modelrunnertask',
            name='buffer',
        ),
        migrations.RemoveField(
            model_name='modelrunnertask',
            name='merge_detections',
        ),
        migrations.RemoveField(
            model_name='modelrunnertask',
            name='overwrite',
        ),
        migrations.RemoveField(
            model_name='modelrunnertask',
            name='step_size',
        ),
        migrations.RemoveField(
            model_name='modelrunnertask',
            name='threshold',
        ),
        migrations.AddField(
            model_name='modelrunnertask',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Model parameters including threshold, step_size, batch_size, merge_detections, overwrite, and buffer'),
        ),
    ]
