# Generated by Django 4.2.1 on 2025-06-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelrunner', '0003_remove_modelrunnertask_batch_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='file',
        ),
    ]
