# Generated by Django 4.2.1 on 2025-08-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelrunner', '0004_remove_detection_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='filename',
            field=models.CharField(default='default', help_text='Filename', max_length=255),
            preserve_default=False,
        ),
    ]
