---
- name: Set up Mailcow on the server
  hosts: maipl-mail
  become: yes
  vars:
    mailcow_storage_path: /mnt/mail
    mailcow_repo: https://github.com/mailcow/mailcow-dockerized
    mailcow_directory: /opt/mailcow
    docker_compose_version: latest  # Use 'plugin' for Docker Compose plugin, 'standalone' for standalone
    use_selinux: false  # Set to true if using SELinux
    mtu_value: 1450  # Modify this value if using a non-standard MTU

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - git
        state: present
        update_cache: yes

    - name: Install Docker Compose plugin
      apt:
        name: docker-compose-plugin
        state: present
      when: docker_compose_version == 'plugin'

    - name: Install Docker Compose standalone
      shell: |
        LATEST=$(curl -Ls -w %{url_effective} -o /dev/null https://github.com/docker/compose/releases/latest) && \
        LATEST=${LATEST##*/} && \
        curl -L https://github.com/docker/compose/releases/download/$LATEST/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose && \
        chmod +x /usr/local/bin/docker-compose
      when: docker_compose_version == 'standalone'

    - name: Clone Mailcow repository
      git:
        repo: "{{ mailcow_repo }}"
        dest: "{{ mailcow_directory }}"
        version: master

    - name: Create Mailcow storage directory
      file:
        path: "{{ mailcow_storage_path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Configure MTU settings if needed
      lineinfile:
        path: "{{ mailcow_directory }}/docker-compose.yml"
        regexp: 'com.docker.network.driver.mtu'
        line: "com.docker.network.driver.mtu: {{ mtu_value }}"
        insertafter: 'driver_opts:'
      when: mtu_value != 1500

    - name: Configure SELinux for Docker if enabled
      block:
        - name: Ensure container-selinux package is installed
          yum:
            name: container-selinux
            state: present
          when: ansible_os_family == 'RedHat'

        - name: Enable SELinux in Docker
          lineinfile:
            path: /etc/docker/daemon.json
            line: '"selinux-enabled": true'
            create: yes
            insertbefore: EOF
            state: present

        - name: Restart Docker to apply SELinux settings
          service:
            name: docker
            state: restarted
      when: use_selinux

