---
- name: Deploy Database
  hosts: database_prod
  become: true
  
  pre_tasks:
    - name: Include vault variables
      include_vars:
        file: "../inventory/prod/group_vars/vault.yml"
      no_log: true

  roles:
    - database