server {
        listen       3300;
        server_name  test-annotation.maipl-dev.com;

        location / {
            root /usr/share/nginx/html/annotation-tool;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }

        location ~ \.js$ {
            root /usr/share/nginx/html/annotation-tool;
            add_header Content-Type application/javascript;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html/annotation-tool;
        }
    }

