# Generated by Django 4.2.1 on 2023-06-23 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
    ]
