# Generated by Django 4.2.1 on 2023-06-23 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0001_initial'),
        ('annotation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.batch'),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='segment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.segment'),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processedaudio',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.batch'),
        ),
        migrations.AddField(
            model_name='processedaudio',
            name='segment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.segment'),
        ),
        migrations.AddField(
            model_name='processedaudio',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='batches', to='annotation.segment'),
        ),
        migrations.AddField(
            model_name='batch',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.batch'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.segment'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
