# Generated by Django 4.2.1 on 2023-08-02 02:12

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedaudio',
            name='audio',
            field=models.FileField(storage=django_minio_backend.models.MinioBackend(replace_existing=True), upload_to=''),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='image',
            field=models.FileField(storage=django_minio_backend.models.MinioBackend(replace_existing=True), upload_to=''),
        ),
    ]
