# Generated by Django 4.2.1 on 2023-08-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_alter_annotation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='fields',
        ),
    ]
