# Generated by Django 4.2.1 on 2023-08-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0007_remove_annotation_comments_remove_annotation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='form',
            field=models.TextField(blank=True, null=True),
        ),
    ]
