# Generated by Django 4.2.1 on 2023-11-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0008_batch_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
