# Generated by Django 4.2.1 on 2023-11-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_batch_task_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['id']},
        ),
    ]
