# Generated by Django 4.2.1 on 2023-11-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_alter_file_file'),
        ('annotation', '0010_alter_batch_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='segments',
        ),
        migrations.AddField(
            model_name='batch',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='batches', to='file.file'),
        ),
        migrations.AddField(
            model_name='segment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='annotation.batch'),
        ),
    ]
