# Generated by Django 4.2.1 on 2023-12-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_remove_batch_segments_batch_files_segment_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='form',
            field=models.JSONField(),
        ),
    ]
