# Generated by Django 4.2.1 on 2023-12-18 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_alter_file_file'),
        ('annotation', '0012_alter_batch_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='files',
            new_name='filelist',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='form',
        ),
        migrations.AddField(
            model_name='batch',
            name='annotation_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
        migrations.AddField(
            model_name='batch',
            name='annotation_file_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='segment_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
