# Generated by Django 4.2.1 on 2023-12-20 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_alter_file_file'),
        ('annotation', '0013_rename_files_batch_filelist_remove_batch_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='import_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_batches', to='file.file'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='annotation_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file'),
        ),
    ]
