# Generated by Django 4.2.1 on 2024-02-26 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0014_batch_import_file_alter_batch_annotation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='shared_to',
            field=models.ManyToManyField(blank=True, related_name='batch_shared_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('batch_name', 'user_id')},
        ),
    ]
