# Generated by Django 4.2.1 on 2024-03-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0015_batch_shared_to_alter_batch_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['id'], 'permissions': [('view_annotations_all', 'Can view all annotations'), ('edit_annotations_all', 'Can edit all annotations'), ('delete_annotations_all', 'Can delete all annotations'), ('view_annotation', 'Can view annotation'), ('edit_annotation', 'Can edit annotation'), ('delete_annotation', 'Can delete annotation')]},
        ),
    ]
