# Generated by Django 4.2.1 on 2024-05-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0016_alter_batch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.IntegerField(unique=True)),
                ('permissions', models.ManyToManyField(related_name='roles', to='annotation.permission')),
            ],
        ),
    ]
