# Generated by Django 4.2.1 on 2024-05-12 15:10

from django.db import migrations


def create_roles_and_permissions(apps, schema_editor):
    Role = apps.get_model("annotation", "Role")
    Permission = apps.get_model("annotation", "Permission")

    # Create the permissions
    view_annotations_all_permission = Permission.objects.create(
        name="view_annotations_all", description="Can view all annotations"
    )
    edit_annotations_all_permission = Permission.objects.create(
        name="edit_annotations_all", description="Can edit all annotations"
    )
    delete_annotations_all_permission = Permission.objects.create(
        name="delete_annotations_all", description="Can delete all annotations"
    )
    view_annotation_permission = Permission.objects.create(
        name="view_annotation", description="Can view annotation"
    )
    edit_annotation_permission = Permission.objects.create(
        name="edit_annotation", description="Can edit annotation"
    )
    delete_annotation_permission = Permission.objects.create(
        name="delete_annotation", description="Can delete annotation"
    )

    # Create roles
    viewer_role = Role.objects.create(name="Viewer", code=1)
    contributor_role = Role.objects.create(name="Contributor", code=2)
    viewer_contributor_role = Role.objects.create(name="Viewer-Contributor", code=3)
    manager_role = Role.objects.create(name="Manager", code=4)

    # Assign the permissions to the roles
    viewer_role.permissions.add(view_annotations_all_permission)
    contributor_role.permissions.add(
        view_annotation_permission,
        edit_annotation_permission,
        delete_annotation_permission,
    )
    viewer_contributor_role.permissions.add(
        view_annotations_all_permission,
        view_annotation_permission,
        edit_annotation_permission,
        delete_annotation_permission,
    )
    manager_role.permissions.add(
        view_annotations_all_permission,
        edit_annotations_all_permission,
        delete_annotations_all_permission,
        view_annotation_permission,
        edit_annotation_permission,
        delete_annotation_permission,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0017_permission_role"),
    ]

    operations = [
        migrations.RunPython(create_roles_and_permissions),
    ]
