# Generated by Django 4.2.1 on 2024-06-04 03:10

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0019_alter_batch_options_userrolebatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedaudio',
            name='audio',
            field=models.FileField(storage=django_minio_backend.models.MinioBackend(max_length=255, replace_existing=True), upload_to=''),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='image',
            field=models.FileField(storage=django_minio_backend.models.MinioBackend(max_length=255, replace_existing=True), upload_to=''),
        ),
    ]
