# Generated by Django 4.2.1 on 2024-06-04 03:16

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0020_alter_processedaudio_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedaudio',
            name='audio',
            field=models.FileField(max_length=255, storage=django_minio_backend.models.MinioBackend(bucket_name='audio', replace_existing=True), upload_to=''),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='image',
            field=models.FileField(max_length=255, storage=django_minio_backend.models.MinioBackend(bucket_name='image', replace_existing=True), upload_to=''),
        ),
    ]
