# Generated by Django 4.2.1 on 2025-01-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0021_alter_processedaudio_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='frequency_axis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
