# Generated by Django 4.2.1 on 2025-03-13 01:36

import annotation.models
from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0022_batch_frequency_axis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedaudio',
            name='audio',
            field=models.FileField(max_length=255, storage=django_minio_backend.models.MinioBackend(replace_existing=True), upload_to=annotation.models.upload_to_audio),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='image',
            field=models.FileField(max_length=255, storage=django_minio_backend.models.MinioBackend(replace_existing=True), upload_to=annotation.models.upload_to_image),
        ),
    ]
