# Generated by Django 4.2.1 on 2025-03-20 16:17

import annotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0023_alter_processedaudio_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedaudio',
            name='audio',
            field=models.FileField(max_length=255, storage=annotation.models.get_storage, upload_to=annotation.models.upload_to_audio),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='image',
            field=models.FileField(max_length=255, storage=annotation.models.get_storage, upload_to=annotation.models.upload_to_image),
        ),
    ]
