# Generated by Django 4.2.1 on 2025-03-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0024_alter_processedaudio_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='image_type',
            field=models.CharField(default='spectrogram', max_length=255),
        ),
    ]
