# Generated by Django 4.2.1 on 2024-02-18 20:06

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name='admin')
    Group.objects.create(name='user')
    Group.objects.create(name='guest')

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
