# Use an official Python runtime as a parent image
FROM python:3.10.8
ENV PYTHONUNBUFFERED 1

# Set the working directory to /backend
WORKDIR /backend
COPY src/requirements.txt requirements.txt

RUN apt-get update 

# Install HDF5 C library
RUN apt-get install -y --no-install-recommends libhdf5-serial-dev

# Install sndfile (needed by librosa)
RUN apt-get install -y --no-install-recommends libsndfile1

RUN apt-get install -y inotify-tools

RUN pip install --upgrade -v pip
RUN pip install -r requirements.txt

# Install Scipy>=1.6.0 and aural-features
RUN pip install scipy>=1.6.0
RUN pip install aural-features

RUN mkdir -p /cache
RUN mkdir -p /temp
RUN mkdir -p /logs
RUN mkdir -p /tasks

COPY src/. .
