---
- hosts: maipl-file-cache
  vars:
    nfs_server: 192.168.239.27
  tasks:
    - name: Install NFS server
      apt:
        name: nfs-kernel-server
        state: present

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - /mnt/dev_storage
        - /mnt/prod_storage

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: "{{ item }}"
        create: yes
      loop:
        - "/mnt/dev_storage *(rw,sync,no_subtree_check)"
        - "/mnt/prod_storage *(rw,sync,no_subtree_check)"

    - name: Apply NFS exports
      command: exportfs -a

    - name: Start and enable NFS server
      systemd:
        name: nfs-kernel-server
        state: started
        enabled: true

- hosts: backends,workers
  vars:
    nfs_server: 192.168.239.27
  tasks:
    - name: Install NFS client
      apt:
        name: nfs-common
        state: present

    - name: Create mount points
      file:
        path: /mnt/file_cache
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Add entries to fstab with IP address
      lineinfile:
        path: /etc/fstab
        line: "{{ nfs_server }}:/mnt/prod_storage /mnt/file_cache nfs defaults 0 0"

    - name: Mount NFS share /mnt/file_cache
      command: mount -t nfs {{ nfs_server }}:/mnt/prod_storage /mnt/file_cache

    - name: Verify NFS mounts
      shell: df -h | grep /mnt

- hosts: maipl-backend-dev
  vars:
    nfs_server: 192.168.239.27
  tasks:
    - name: Install NFS client
      apt:
        name: nfs-common
        state: present

    - name: Create mount points
      file:
        path: /mnt/file_cache
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Add entries to fstab with IP address
      lineinfile:
        path: /etc/fstab
        line: "{{ nfs_server }}:/mnt/dev_storage /mnt/file_cache nfs defaults 0 0"

    - name: Mount NFS share /mnt/file_cache
      command: mount -t nfs {{ nfs_server }}:/mnt/dev_storage /mnt/file_cache

    - name: Verify NFS mounts
      shell: df -h | grep /mnt