# Generated by Django 4.2.1 on 2023-06-23 15:12

import django_minio_backend.models
from django.db import migrations, models

import file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=django_minio_backend.models.MinioBackend(), upload_to=file.models.upload_to)),
                ('maipl_folder', models.CharField(max_length=255)),
                ('meta', models.JSONField()),
                ('path', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('tag', models.CharField(default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
