# Generated by Django 4.2.1 on 2023-07-27 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0003_sharedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='shared_files',
            field=models.ManyToManyField(related_name='shared_files', through='file.SharedFile', to=settings.AUTH_USER_MODEL),
        ),
    ]
