# Generated by Django 4.2.1 on 2023-08-02 02:12

import django_minio_backend.models
from django.db import migrations, models

import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_file_shared_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='files', replace_existing=True), upload_to=file.models.upload_to),
        ),
    ]
