# Generated by Django 4.2.1 on 2024-01-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
