# Generated by Django 4.2.1 on 2024-02-12 19:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0006_alter_file_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='shared_files',
            new_name='shared_with',
        ),
        migrations.RenameField(
            model_name='sharedfile',
            old_name='shared_with',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='sharedfile',
            unique_together={('file', 'user')},
        ),
    ]
