# Generated by Django 4.2.1 on 2024-02-26 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0007_rename_shared_files_file_shared_with_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='shared_with',
            field=models.ManyToManyField(related_name='file_shared_with', through='file.SharedFile', to=settings.AUTH_USER_MODEL),
        ),
    ]
