# Generated by Django 4.2.1 on 2024-02-26 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0008_alter_file_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='file',
            name='shared_to',
            field=models.ManyToManyField(related_name='file_shared_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SharedFile',
        ),
    ]
