# Generated by Django 4.2.1 on 2024-03-22 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0009_remove_file_shared_with_file_shared_to_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('user_id', 'path')},
        ),
    ]
