# Generated by Django 4.2.1 on 2024-06-04 02:52

from django.db import migrations, models
import django_minio_backend.models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_alter_file_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, storage=django_minio_backend.models.MinioBackend(bucket_name='files', replace_existing=True), upload_to=file.models.upload_to),
        ),
    ]
