# Generated by Django 4.2.1 on 2025-03-13 01:36

from django.db import migrations, models
import django_minio_backend.models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, storage=django_minio_backend.models.MinioBackend(bucket_name='maipl-dev', replace_existing=True), upload_to=file.models.upload_to),
        ),
    ]
