# Generated by Django 4.2.1 on 2025-03-20 16:12

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, storage=file.models.get_storage, upload_to=file.models.upload_to),
        ),
    ]
