# tasks file for roles/minio
---
- name: Include volume setup tasks
  import_tasks: volume.yml

- name: Include Docker installation tasks
  import_tasks: docker.yml

- name: Include Minio deployment tasks
  import_tasks: deploy.yml

- name: Include Monitoring tasks
  import_tasks: monitoring.yml

- name: Include Grafana tasks
  import_tasks: grafana.yml

- name: Include Verify tasks
  import_tasks: verify.yml
