---
- name: Deploy Minio with Docker
  hosts: all
  become: true
  vars:
    minio_volume_device: /dev/vdb
    minio_data_dir: /data/minio
    minio_config_dir: /etc/minio
    docker_compose_version: "2.17.2"
    grafana_url: "{{ grafana_url }}"
    loki_url: "{{ loki_url }}"

  roles:
    - minio