# Generated by Django 4.2.1 on 2024-10-11 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0011_alter_file_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dataset_config', models.JSONField()),
                ('options', models.JSONField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('STARTED', 'Started'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('REVOKED', 'Revoked'), ('SUCCESS', 'Success')], default='CREATED', max_length=255)),
                ('celery_task_id', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('local_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_file', models.ForeignKey(blank=True, default=None, help_text='Dataset file to use for training', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_file_tasks', to='file.file')),
                ('model_file', models.ForeignKey(blank=True, default=None, help_text='Model file generated by the training task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_file_train_tasks', to='file.file')),
                ('recipe_file', models.ForeignKey(blank=True, default=None, help_text='Recipe file to use for training', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_file_tasks', to='file.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
