# Generated by Django 4.2.1 on 2024-10-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltrainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtask',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
