# Generated by Django 4.2.1 on 2024-10-11 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modeltrainer', '0002_alter_trainingtask_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
