# Generated by Django 4.2.1 on 2025-01-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltrainer', '0003_alter_trainingtask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtask',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('STARTED', 'Started'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('REVOKED', 'Revoked')], default='CREATED', max_length=255),
        ),
    ]
