name: Backend and Worker Build and Deploy to Live instance

on:
  push:
    branches:
      - backend-dev
    paths:
      - backend/**
      - .github/workflows/backend-dev.yml

jobs:
  build:
    runs-on: self-hosted
    env:
      REGISTRY_URL: ${{ vars.REGISTRY_URL }}
      BACKEND_HOST: ${{ vars.BACKEND_STAGING_HOST }}
      WORKER_HOST: ${{ vars.WORKER_STAGING_HOST }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}

    steps:
      - uses: actions/checkout@v4

      - name: login to registry
        run: |
          echo $REGISTRY_PASSWORD | docker login $REGISTRY_URL --username $REGISTRY_USERNAME --password-stdin 

      - name: Build backend and worker
        working-directory: backend/compose
        run: docker compose -f docker-compose.build.yml build

      - name: Push backend and worker to registry
        run: |
          docker push $REGISTRY_URL/maipl-backend/ketos-backend:dev
          docker push $REGISTRY_URL/maipl-backend/ketos-worker:dev

      - name: Deploy backend and worker
        run: |
          # Create directory if it doesn't exist
          ssh ubuntu@$BACKEND_HOST "mkdir -p ~/backend"
          ssh ubuntu@$WORKER_HOST "mkdir -p ~/worker"

          # Create .env file directly from the secret
          echo "${{ secrets.STAGING_ENV_FILE }}" > backend/.env

          # Copy both compose file
          scp backend/compose/docker-compose.backend.yml ubuntu@$BACKEND_HOST:~/backend/docker-compose.yml
          scp backend/.env ubuntu@$BACKEND_HOST:~/backend/.env
          scp backend/compose/docker-compose.worker.yml ubuntu@$WORKER_HOST:~/worker/docker-compose.yml
          scp backend/.env ubuntu@$WORKER_HOST:~/worker/.env

          # Deploy
          ssh ubuntu@$BACKEND_HOST "cd ~/backend && \
            docker compose pull && \
            docker compose down --remove-orphans && \
            docker compose up -d && \
            docker system prune -f"

          ssh ubuntu@$WORKER_HOST "cd ~/worker && \
            docker compose pull && \
            docker compose down --remove-orphans && \
            docker compose up -d && \
            docker system prune -f"
    
